// Skylighting's syntaxes by name, each with the file-name globs it is
// for, in the order of its syntax map. Generated from skylighting-core
// 0.14.7's syntax definitions, taking only these.

// cspell:disable

export const SYNTAXES = [
  ['ABC', ['*.abc', '*.ABC']],
  ['ASN.1', ['*.asn', '*.asn1']],
  ['ASP', ['*.asp']],
  ['ATS', ['*.dats', '*.sats', '*.hats']],
  ['AWK', ['*.awk']],
  ['ActionScript 2.0', ['*.as']],
  ['Ada', ['*.adb', '*.ads', '*.ada', '*.a']],
  ['Agda', ['*.agda']],
  ['Alerts', []],
  [
    'Apache Configuration',
    [
      'httpd.conf',
      'httpd2.conf',
      'apache.conf',
      'apache2.conf',
      '.htaccess*',
      '.htpasswd*',
    ],
  ],
  [
    'Bash',
    [
      '*.sh',
      '*.bash',
      '*.ebuild',
      '*.eclass',
      '*.exlib',
      '*.exheres-0',
      '.bashrc',
      '.bash_profile',
      '.bash_login',
      '.profile',
      'PKGBUILD',
      'APKBUILD',
    ],
  ],
  ['BibTeX', ['*.bib']],
  ['Boo', ['*.boo']],
  ['C', ['*.c', '*.C', '*.h']],
  ['C#', ['*.cs', '*.ashx']],
  [
    'C++',
    [
      '*.c++',
      '*.cxx',
      '*.cpp',
      '*.cc',
      '*.C',
      '*.h',
      '*.hh',
      '*.H',
      '*.h++',
      '*.hxx',
      '*.hpp',
      '*.hcc',
      '*.inl',
      '*.pde',
      '*.moc',
      '*.mpp',
      '*.ixx',
      '*.cppm',
      '*.cxxm',
      '*.c++m',
      '*.ccm',
    ],
  ],
  ['CMake', ['CMakeLists.txt', '*.cmake', '*.cmake.in']],
  ['CSS', ['*.css']],
  ['ChangeLog', ['ChangeLog']],
  ['Clojure', ['*.clj', '*.cljs', '*.cljc']],
  ['CoffeeScript', ['Cakefile', '*.coffee', '*.coco', '*.cson']],
  ['ColdFusion', ['*.cfm', '*.cfc', '*.cfml', '*.dbm']],
  ['Comments', []],
  ['Common Lisp', ['*.lisp', '*.cl', '*.lsp', '*.el']],
  ['Crystal', ['*.cr']],
  ['Curry', ['*.curry']],
  ['D', ['*.d', '*.D', '*.di', '*.DI']],
  ['DTD', ['*.dtd']],
  ['Dart', ['*.dart']],
  ['Debian Control', ['control']],
  ['Default', ['*.txt']],
  ['Diff', ['*.diff', '*patch', '*.rej']],
  ['Django HTML Template', ['*.htm', '*.html']],
  ['Dockerfile', ['Dockerfile', 'Containerfile']],
  ['Doxygen', ['*.dox', '*.doxygen']],
  ['DoxygenLua', []],
  ['Eiffel', ['*.e']],
  ['Elixir', ['*.ex', '*.exs', '*.eex', '*.xml.eex', '*.js.eex', '*.heex']],
  ['Elm', ['*.elm']],
  ['Email', ['*.eml', '*.email', '*.emlx', '*.mbox', '*.mbx']],
  ['Erlang', ['*.erl']],
  ['FSharp', ['*.fs', '*.fsi', '*.fsx']],
  [
    'Fortran (Fixed Format)',
    ['*.f', '*.F', '*.for', '*.FOR', '*.fpp', '*.FPP'],
  ],
  [
    'Fortran (Free Format)',
    ['*.f90', '*.F90', '*.f95', '*.F95', '*.f03', '*.F03', '*.f08', '*.F08'],
  ],
  ['GAP', ['*.gd', '*.gi', '*.g']],
  [
    'GCCExtensions',
    [
      '*.c++',
      '*.cxx',
      '*.cpp',
      '*.cc',
      '*.C',
      '*.h',
      '*.hh',
      '*.H',
      '*.h++',
      '*.hxx',
      '*.hpp',
      '*.hcc',
    ],
  ],
  [
    'GLSL',
    [
      '*.glsl',
      '*.vert',
      '*.vs',
      '*.frag',
      '*.fs',
      '*.geom',
      '*.gs',
      '*.tcs',
      '*.tes',
    ],
  ],
  ['GNU Assembler', ['*.s', '*.S']],
  ['GNU M4', ['*.m4']],
  ['GPRBuild', ['*.gpr']],
  ['Gleam', ['*.gleam']],
  ['Go', ['*.go']],
  ['Godot', ['*.gd']],
  ['GraphQL', ['*.graphql']],
  ['Groovy', ['*.groovy', '*.gradle', '*.gvy', 'Jenkinsfile']],
  ['HTML', ['*.htm', '*.html', '*.shtml', '*.shtm', '*.aspx']],
  ['Hamlet', ['*.hamlet']],
  ['Haskell', ['*.hs', '*.chs', '*.hs-boot']],
  ['Haxe', ['*.hx', '*.Hx', '*.hX', '*.HX']],
  [
    'INI Files',
    [
      '*.ini',
      '*.INI',
      '*.cfg',
      '*.pls',
      '*.kcfgc',
      '.gitattributes*',
      '.gitconfig*',
      '.gitmodules*',
      '.editorconfig*',
    ],
  ],
  [
    'ISO C++',
    [
      '*.c++',
      '*.cxx',
      '*.cpp',
      '*.cc',
      '*.C',
      '*.cu',
      '*.h',
      '*.hh',
      '*.H',
      '*.h++',
      '*.hxx',
      '*.hpp',
      '*.hcc',
      '*.cuh',
      '*.inl',
      '*.ino',
      '*.pde',
      '*.moc',
      '*.mpp',
      '*.ixx',
      '*.cppm',
      '*.cxxm',
      '*.c++m',
      '*.ccm',
    ],
  ],
  ['Idris', ['*.idr']],
  ['Intel x86 (FASM)', ['*.asm', '*.inc', '*.fasm']],
  ['Intel x86 (NASM)', ['*.asm']],
  ['J', ['*.ijs', '*.ijt', '*.IJS', '*.IJT']],
  [
    'JSON',
    [
      '*.json',
      '*.jsonl',
      '*.ndjson',
      '.kateproject',
      '.arcconfig',
      '*.geojson',
      '*.gltf',
      '*.theme',
      '*.cast',
    ],
  ],
  ['JSP', ['*.jsp', '*.JSP']],
  ['Java', ['*.java']],
  ['JavaScript', ['*.js', '*.mjs', '*.cjs', '*.kwinscript', '*.julius']],
  ['JavaScript React (JSX)', ['*.jsx']],
  ['Javadoc', []],
  ['Julia', ['*.jl']],
  ['Kotlin', ['*.kt', '*.kts']],
  ['LLVM', ['*.ll']],
  [
    'LaTeX',
    [
      '*.tex',
      '*.ltx',
      '*.dtx',
      '*.sty',
      '*.cls',
      '*.bbx',
      '*.cbx',
      '*.lbx',
      '*.tikz',
      '*.pgf',
    ],
  ],
  ['Lex/Flex', ['*.l', '*.lex', '*.flex']],
  ['LilyPond', ['*.ly', '*.LY', '*.ily', '*.ILY', '*.lyi', '*.LYI']],
  ['Literate Curry', ['*.lcurry']],
  ['Literate Haskell', ['*.lhs']],
  ['Lua', ['*.lua', '*.rockspec']],
  ['MIPS Assembler', ['*.s']],
  ['MS-DOS Batch', ['*.bat', '*.cmd']],
  [
    'Makefile',
    [
      'GNUmakefile',
      'Makefile',
      'makefile',
      'GNUmakefile.*',
      'Makefile.*',
      'makefile.*',
      '*.mk',
    ],
  ],
  ['Markdown', ['*.md', '*.mmd', '*.markdown', '*.md.html']],
  ['Mathematica', ['*.nb']],
  ['Matlab', ['*.m', '*.M']],
  ['Maxima', ['*.mac', '*.MAC', '*.dem', '*.DEM']],
  ['MediaWiki', ['*.mediawiki']],
  ['Metapost/Metafont', ['*.mp', '*.mps', '*.mpost', '*.mf']],
  ['Modelines', []],
  ['Modula-2', ['*.mod', '*.def']],
  ['Modula-3', ['*.m3', '*.i3', '*.ig', '*.mg']],
  ['MonoBasic', ['*.vb']],
  [
    'Mustache/Handlebars (HTML)',
    [
      '*.mustache',
      '*.handlebars',
      '*.hbs',
      '*.ractive',
      '*.hogan',
      '*.hulk',
      '*.html.mst',
      '*.html.mu',
      '*.html.rac',
    ],
  ],
  ['Nim', ['*.nim', '*.nims', '*.nimble']],
  ['Nix', ['*.nix']],
  ['Objective Caml', ['*.ml', '*.mli']],
  ['Objective-C', ['*.m', '*.h']],
  ['Objective-C++', ['*.mm', '*.M', '*.h']],
  ['Octave', ['*.octave', '*.m', '*.M']],
  ['Odin', ['*.odin']],
  ['OpenCL', ['*.cl']],
  ['Org Mode', ['*.org']],
  ['PHP/PHP', []],
  ['POV-Ray', ['*.inc', '*.pov']],
  ['Pascal', ['*.p', '*.pas', '*.pp']],
  ['Perl', ['*.pl', '*.PL', '*.pm']],
  ['Pike', ['*.pike']],
  ['PostScript', ['*.ps', '*.ai', '*.eps']],
  ['PowerShell', ['*.ps1', '*.psm1', '*.psd1']],
  ['Prolog', ['*.prolog', '*.dcg', '*.pro']],
  ['Protobuf', ['*.proto']],
  ['Pure', ['*.pure']],
  ['PureBasic', ['*.pb', '*.pbi']],
  ['PureScript', ['*.purs']],
  [
    'Python',
    [
      '*.py',
      '*.pyw',
      '*.pyi',
      'SConstruct',
      'SConscript',
      '*.FCMacro',
      '*.sage',
    ],
  ],
  ['QML', ['*.qml', '*.qmltypes']],
  ['R Script', ['*.R', '*.r', '*.S', '*.s', '*.q']],
  ['RELAX NG', ['*.rng', '*.RNG']],
  ['Racket', ['*.rkt', '*.scrbl']],
  [
    'Raku',
    [
      '*.raku',
      '*.rakumod',
      '*.rakudoc',
      '*.rakutest',
      '*.pl6',
      '*.PL6',
      '*.p6',
      '*.pm6',
      '*.pod6',
    ],
  ],
  ['RelaxNG-Compact', ['*.rnc']],
  ['Roff', []],
  [
    'Ruby',
    [
      '*.rb',
      '*.rjs',
      '*.rxml',
      '*.xml.erb',
      '*.js.erb',
      '*.rake',
      'Rakefile',
      'Gemfile',
      '*.gemspec',
      'Vagrantfile',
    ],
  ],
  ['Ruby/Rails/RHTML', ['*.rhtml', '*.RHTML', '*.erb']],
  ['Rust', ['*.rs']],
  ['SASS', ['*.sass']],
  ['SCSS', ['*.scss']],
  ['SGML', ['*.sgml']],
  ['SML', ['*.sml', '*.ml']],
  ['SPDX-Comments', []],
  ['SQL', ['*.sql', '*.SQL', '*.ddl', '*.DDL']],
  ['SQL (MySQL)', ['*.sql', '*.SQL', '*.ddl', '*.DDL']],
  ['SQL (PostgreSQL)', ['*.sql', '*.SQL', '*.ddl', '*.DDL']],
  ['Scala', ['*.scala', '*.sbt']],
  ['Scheme', ['*.scm', '*.ss', '*.scheme', '*.guile', '*.chicken', '*.meta']],
  ['Stan', ['*.stan', '*.stanfunctions']],
  ['Stata', ['*.do', '*.ado', '*.doh', '*.DO', '*.ADO', '*.DOH']],
  ['Swift', ['*.swift']],
  ['SystemVerilog', ['*.sv', '*.svh']],
  ['TLA+', ['*.tla']],
  [
    'TOML',
    [
      'Cargo.lock',
      '*.toml',
      '*.rc',
      '*.conf',
      '*.cfg',
      '*.cf',
      '*.cnf',
      '*.ini',
      'mirrorlist',
    ],
  ],
  ['Tcl/Tk', ['*.tcl', '*.tk']],
  [
    'Tcsh',
    [
      '*.csh',
      '*.tcsh',
      'csh.cshrc',
      'csh.login',
      '.tcshrc',
      '.cshrc',
      '.login',
    ],
  ],
  ['Terraform', ['*.tf', '*.tfvars']],
  ['Texinfo', ['*.texi']],
  [
    'Troff Mandoc',
    [
      '*.1',
      '*.2',
      '*.3',
      '*.4',
      '*.5',
      '*.6',
      '*.7',
      '*.8',
      '*.1m',
      '*.3x',
      '*.tmac',
    ],
  ],
  ['TypeScript', ['*.ts', '*.mts', '*.cts']],
  ['Typst', ['*.typ']],
  ['VHDL', ['*.vhdl', '*.vhd']],
  ['Verilog', ['*.v', '*.V', '*.vl']],
  [
    'XML',
    [
      '*.page',
      '*.docbook',
      '*.xml',
      '*ui.rc',
      '*.daml',
      '*.rdf',
      '*.rss',
      '*.xspf',
      '*.xsd',
      '*.svg',
      '*.ui',
      '*.kcfg',
      '*.qrc',
      '*.wsdl',
      '*.scxml',
      '*.xbel',
      '*.dae',
      '*.sch',
      '*.brd',
      '*.fb2',
    ],
  ],
  ['XUL', ['*.xul', '*.xbl']],
  ['YAML', ['*.yaml', '*.yml', '.clang-format', '.clang-tidy']],
  ['Yacc/Bison', ['*.y', '*.yy', '*.ypp', '*.y++']],
  ['Zig', ['*.zig']],
  [
    'Zsh',
    ['*.sh', '*.zsh', '.zshrc', '.zprofile', '.zlogin', '.zlogout', '.profile'],
  ],
  ['dot', ['*.dot']],
  ['noweb', ['*.w', '*.nw']],
  ['reStructuredText', ['*.rst']],
  ['scilab', ['*.sci', '*.sce']],
  ['sed', ['*.sed']],
  ['x.org Configuration', ['xorg.conf']],
  ['xslt', ['*.xsl', '*.xslt']],
];
